# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Kent
email: rob@robkent.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Just a few little developer-y bits
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robkent.co.uk" # the base hostname & protocol for your site
twitter_username: kent_robert
github_username:  robertkent

# Build settings
markdown: kramdown