# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Kent
email: rob@robkent.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Just a few little developer-y bits
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robkent.co.uk" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Robert Kent'
bio: >
  Just a web developer
author_image: "/assets/images/author.jpg"
twitter_username: kent_robert
github_username:  robertkent

permalink: none

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-sitemap
