(window.AMP = window.AMP || []).push(function(AMP) {var process={env:{NODE_ENV:"production"}};var f={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};f.global=f.getGlobal(this);f.initSymbol=function(){f.global.Symbol||(f.global.Symbol=f.Symbol);f.initSymbol=function(){}};f.symbolCounter_=0;f.Symbol=function(a){return"jscomp_symbol_"+a+f.symbolCounter_++};f.initSymbolIterator=function(){f.initSymbol();f.global.Symbol.iterator||(f.global.Symbol.iterator=f.global.Symbol("iterator"));f.initSymbolIterator=function(){}};
f.makeIterator=function(a){f.initSymbolIterator();if(a[f.global.Symbol.iterator])return a[f.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};f.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};f.arrayFromIterable=function(a){return a instanceof Array?a:f.arrayFromIterator(f.makeIterator(a))};
f.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};f.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(f.global.Object.defineProperties){var e=f.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&f.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};var h={},l=null;
h.getMode=function(){if(l)return l;var a;if(window.context&&window.context.mode)a=window.context.mode;else{a=("localhost"==location.hostname||location.ancestorOrigins&&location.ancestorOrigins[0]&&0==location.ancestorOrigins[0].indexOf("http://localhost:"))&&!!document.querySelector('script[src*="/dist/"],script[src*="/base/"]');var b=location.originalHash||location.hash,c=Object.create(null);if(b){if(0==b.indexOf("?")||0==b.indexOf("#"))b=b.substr(1);for(var b=b.split("&"),d=0;d<b.length;d++){var e=
b[d],g=e.indexOf("="),k=void 0,t=void 0;-1!=g?(k=decodeURIComponent(e.substring(0,g)).trim(),t=decodeURIComponent(e.substring(g+1)).trim()):(k=decodeURIComponent(e).trim(),t="");k&&(c[k]=t)}}a={localDev:a,development:"1"==c.development||window.AMP_DEV_MODE,minified:"production"==process.env.NODE_ENV,test:window.AMP_TEST,log:c.log}}return l=a};h.setModeForTesting=function(a){l=a};var m={},n=(new Date).getTime(),p={OFF:0,ERROR:1,WARN:2,INFO:3,FINE:4};function q(a,b,c){this.win=a.AMP_TEST?a.parent:a;this.levelFunc_=b;this.level_=this.calcLevel_();this.suffix_=c||""}q.prototype.calcLevel_=function(){var a=h.getMode();return this.win.console&&this.win.console.log&&"0"!=a.log?this.win.ENABLE_LOG?p.FINE:a.localDev&&!a.log?p.INFO:this.levelFunc_(a):p.OFF};
q.prototype.msg_=function(a,b,c){if(this.level_!=p.OFF){var d=this.win.console.log;"ERROR"==b?d=this.win.console.error||d:"INFO"==b?d=this.win.console.info||d:"WARN"==b&&(d=this.win.console.warn||d);c.unshift((new Date).getTime()-n,"["+a+"]");d.apply(this.win.console,c)}};q.prototype.isEnabled=function(){return this.level_!=p.OFF};q.prototype.fine=function(a,b){this.level_>=p.FINE&&this.msg_(a,"FINE",Array.prototype.slice.call(arguments,1))};
q.prototype.info=function(a,b){this.level_>=p.INFO&&this.msg_(a,"INFO",Array.prototype.slice.call(arguments,1))};q.prototype.warn=function(a,b){this.level_>=p.WARN&&this.msg_(a,"WARN",Array.prototype.slice.call(arguments,1))};q.prototype.error=function(a,b){if(this.level_>=p.ERROR)this.msg_(a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=u.apply(null,Array.prototype.slice.call(arguments,1));this.prepareError_(c);this.win.setTimeout(function(){throw c;})}};
q.prototype.createError=function(a){var b=u.apply(null,arguments);this.prepareError_(b);return b};
q.prototype.assert=function(a,b,c){var d=void 0;if(!a){var e=(b||"Assertion failed").split("%s"),g=e.shift(),k=g,t=[];""!=g&&t.push(g);for(g=2;g<arguments.length;g++){var r=arguments[g];r&&r.tagName&&(d=r);var F=e.shift();t.push(r);var G=F.trim();""!=G&&t.push(G);r=r instanceof Element?r.tagName.toLowerCase()+(r.id?"#"+r.id:""):r;k+=r+F}e=Error(k);e.fromAssert=!0;e.associatedElement=d;e.messageArray=t;this.prepareError_(e);throw e;}return a};
q.prototype.assertEnumValue=function(a,b,c){for(var d in a)if(a[d]==b)return a[d];this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};q.prototype.prepareError_=function(a){this.suffix_&&(a.message?-1==a.message.indexOf(this.suffix_)&&(a.message+=this.suffix_):a.message=this.suffix_)};function u(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=e:(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}
var v=new q(window,function(a){var b=parseInt(a.log,10);return a.development||1<=b?p.FINE:p.OFF},"\u200b\u200b\u200b"),w=new q(window,function(a){a=parseInt(a.log,10);return 3<=a?p.FINE:2<=a?p.INFO:p.OFF});m.USER_ERROR_SENTINEL="\u200b\u200b\u200b";m.isUserErrorMessage=function(a){return 0<=a.indexOf("\u200b\u200b\u200b")};m.LogLevel=p;m.Log=q;m.rethrowAsync=function(a){var b=u.apply(null,arguments);setTimeout(function(){throw b;})};m.user=v;m.dev=w;var x={},y=Object.create(null),z="Webkit webkit Moz moz ms O o".split(" ");function A(a){return a.charAt(0).toUpperCase()+a.slice(1)}function B(a,b,c){var d=y[b];if(!d||c){d=b;if(void 0===a[b]){var e=A(b);a:{for(var g=0;g<z.length;g++){var k=z[g]+e;if(void 0!==a[k]){e=k;break a}}e=""}void 0!==a[e]&&(d=e)}c||(y[b]=d)}return d}function C(a,b,c,d,e){(b=B(a.style,b,e))&&(a.style[b]=d?c+d:c)}function D(a){return a+"px"}x.camelCaseToTitleCase=A;x.getVendorJsPropertyName=B;x.setStyle=C;
x.getStyle=function(a,b,c){return(b=B(a.style,b,c))?a.style[b]:void 0};x.setStyles=function(a,b){for(var c in b)C(a,c,b[c])};x.toggle=function(a,b){void 0===b&&(b="none"==a.style.display);a.style.display=b?"":"none"};x.px=D;x.translateX=function(a){return"string"==typeof a?"translateX("+a+")":"translateX("+D(a)+")"};x.translate=function(a,b){"number"==typeof a&&(a=D(a));if(void 0===b)return"translate("+a+")";"number"==typeof b&&(b=D(b));return"translate("+a+","+b+")"};
x.scale=function(a){return"scale("+a+")"};var E={};function H(a){this.win=a;this.resolved_=Promise.resolve();this.taskCount_=0;this.canceled_={};this.startTime_=this.now()}H.prototype.now=function(){return Date.now()};H.prototype.timeSinceStart=function(){return this.now()-this.startTime_};H.prototype.delay=function(a,b){if(!b){var c=this,d="p"+this.taskCount_++;this.resolved_.then(function(){c.canceled_[d]?delete c.canceled_[d]:a()});return d}return this.win.setTimeout(a,b)};
H.prototype.cancel=function(a){"string"==typeof a?this.canceled_[a]=!0:this.win.clearTimeout(a)};H.prototype.promise=function(a,b){var c=this,d=null;return(new Promise(function(e,g){d=c.delay(function(){d=-1;e(b)},a);-1==d&&g(Error("Failed to schedule timer."))})).catch(function(a){-1!=d&&c.cancel(d);throw a;})};
H.prototype.timeoutPromise=function(a,b,c){var d=this,e=null,g=(new Promise(function(b,g){e=d.delay(function(){e=-1;g(m.user.createError(c||"timeout"))},a);-1==e&&g(Error("Failed to schedule timer."))})).catch(function(a){-1!=e&&d.cancel(e);throw a;});return b?Promise.race([g,b]):g};var I=new H(window);E.Timer=H;E.timer=I;var J={},K={NODISPLAY:"nodisplay",FIXED:"fixed",FIXED_HEIGHT:"fixed-height",RESPONSIVE:"responsive",CONTAINER:"container",FILL:"fill"},L={"AMP-PIXEL":{width:"1px",height:"1px"},"AMP-ANALYTICS":{width:"1px",height:"1px"},"AMP-AUDIO":null},M={"AMP-ANIM":!0,"AMP-BRIGHTCOVE":!0,"AMP-EMBED":!0,"AMP-IFRAME":!0,"AMP-IMG":!0,"AMP-INSTAGRAM":!0,"AMP-LIST":!0,"AMP-PINTEREST":!0,"AMP-VIDEO":!0};
function N(a){m.user.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)$/.test(a),"Invalid length value: %s",a);return a}J.Layout=K;J.naturalDimensions_=L;J.LOADING_ELEMENTS_=M;J.parseLayout=function(a){for(var b in K)if(K[b]==a)return K[b]};J.getLayoutClass=function(a){return"-amp-layout-"+a};J.isLayoutSizeDefined=function(a){return a==K.FIXED||a==K.FIXED_HEIGHT||a==K.RESPONSIVE||a==K.FILL};J.isInternalElement=function(a){return(a="string"==typeof a?a:a.tagName)&&0==a.toLowerCase().indexOf("i-")};
J.parseLength=function(a){return"number"==typeof a?a+"px":a&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax)?$/.test(a)?/^\d+(\.\d+)?$/.test(a)?a+"px":a:void 0};J.assertLength=N;J.assertLengthOrPercent=function(a){m.user.assert(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|%)$/.test(a),"Invalid length or percent value: %s",a);return a};J.getLengthUnits=function(a){N(a);return m.user.assert(a.match(/[a-z]+/i),"Failed to read units from %s",a)[0]};J.getLengthNumeral=function(a){return parseFloat(a)};
J.hasNaturalDimensions=function(a){a=a.toUpperCase();return void 0!==L[a]};J.getNaturalDimensions=function(a){var b=a.tagName.toUpperCase();m.dev.assert(void 0!==L[b]);if(!L[b]){a=a.ownerDocument;var c=b.replace(/^AMP\-/,""),c=a.createElement(c);c.controls=!0;c.style.position="absolute";c.style.visibility="hidden";a.body.appendChild(c);L[b]={width:(c.offsetWidth||1)+"px",height:(c.offsetHeight||1)+"px"};a.body.removeChild(c)}return L[b]};J.isLoadingAllowed=function(a){return M[a.toUpperCase()]||!1};var O={};function P(a,b,c,d){function e(a){c(a);k()}var g=d||!1,k=void 0,k=function(){a&&a.removeEventListener(b,e,g);e=a=null};a.addEventListener(b,e,g);return k}function Q(a){return a.complete||"complete"==a.readyState}function R(a,b,c){var d=void 0,d=void 0===c?a:E.timer.timeoutPromise(c||0,a);return b?d.then(function(a){b();return a},function(a){b();throw a;}):d}O.listen=function(a,b,c,d){var e=d||!1;a.addEventListener(b,c,e);return function(){a&&a.removeEventListener(b,c,e);a=c=null}};
O.listenOnce=P;O.listenOncePromise=function(a,b,c,d){var e=void 0,g=new Promise(function(d){e=P(a,b,d,c)});return R(g,e,d)};O.isLoaded=Q;O.loadPromise=function(a,b){var c=void 0,d=void 0,e=new Promise(function(b,e){Q(a)?b(a):(c="AUDIO"===a.tagName||"VIDEO"===a.tagName?P(a,"loadstart",function(){return b(a)}):P(a,"load",function(){return b(a)}),d=P(a,"error",function(){e(m.user.createError("Failed HTTP request for %s.",a))}))});return R(e,function(){c&&c();d&&d()},b)};function S(a){AMP.BaseElement.apply(this,arguments)}f.inherits(S,AMP.BaseElement);S.prototype.preconnectCallback=function(a){this.preconnect.url("https://www.youtube.com",a);this.preconnect.url("https://s.ytimg.com",a);this.preconnect.url("https://i.ytimg.com",a)};S.prototype.isLayoutSupported=function(a){return J.isLayoutSizeDefined(a)};S.prototype.renderOutsideViewport=function(){return!1};
S.prototype.buildCallback=function(){var a=this.element.getAttribute("width"),b=this.element.getAttribute("height");this.width_=J.getLengthNumeral(a);this.height_=J.getLengthNumeral(b);this.playerState_=0;this.videoid_=m.user.assert(this.element.getAttribute("data-videoid")||this.element.getAttribute("video-id"),"The data-videoid attribute is required for <amp-youtube> %s",this.element);this.getPlaceholder()||this.buildImagePlaceholder_()};
S.prototype.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe");b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src="https://www.youtube.com/embed/"+encodeURIComponent(this.videoid_)+"?enablejsapi=1";this.applyFillContent(b);b.width=this.width_;b.height=this.height_;this.element.appendChild(b);this.iframe_=b;this.playerReadyPromise_=new Promise(function(b){a.playerReadyResolver_=b});this.getWin().addEventListener("message",function(b){return a.handleYoutubeMessages_(b)});
return O.loadPromise(b).then(function(){return E.timer.promise(300)}).then(function(){return a.listenToFrame_()}).then(function(){return a.playerReadyPromise_})};S.prototype.pauseCallback=function(){this.iframe_&&this.iframe_.contentWindow&&1==this.playerState_&&this.pauseVideo_()};S.prototype.pauseVideo_=function(){this.iframe_.contentWindow.postMessage(JSON.stringify({event:"command",func:"pauseVideo",args:""}),"*")};
S.prototype.handleYoutubeMessages_=function(a){if("https://www.youtube.com"==a.origin&&a.source==this.iframe_.contentWindow){var b=void 0;if(a.data&&0==a.data.indexOf("{")){try{b=JSON.parse(a.data)}catch(c){return}"onReady"==b.event?this.playerReadyResolver_(this.iframe_):"infoDelivery"==b.event&&b.info&&void 0!==b.info.playerState&&(this.playerState_=b.info.playerState)}}};S.prototype.listenToFrame_=function(){this.iframe_.contentWindow.postMessage(JSON.stringify({event:"listening"}),"*")};
S.prototype.buildImagePlaceholder_=function(){var a=new Image,b=this.videoid_;x.setStyles(a,{"object-fit":"cover",visibility:"hidden"});a.src="https://i.ytimg.com/vi/"+encodeURIComponent(this.videoid_)+"/sddefault.jpg#404_is_fine";a.setAttribute("placeholder","");a.width=this.width_;a.height=this.height_;this.element.appendChild(a);this.applyFillContent(a);O.loadPromise(a).then(function(){if(120==a.naturalWidth&&90==a.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){a.src=
"https://i.ytimg.com/vi/"+encodeURIComponent(b)+"/hqdefault.jpg";return O.loadPromise(a)}).then(function(){x.setStyles(a,{visibility:""})})};AMP.registerElement("amp-youtube",S);
});
//# sourceMappingURL=amp-youtube-0.1.js.map
